version: 2

models:
  - name: stg_accounts
    description: Cleaned staging model for SaaS accounts

    columns:
      - name: account_id
        description: Unique account identifier
        tests:
          - not_null
          - unique

      - name: signup_date
        tests:
          - not_null

      - name: seats
        tests:
          - not_null


  - name: stg_subscriptions
    description: Cleaned staging model for SaaS subscriptions

    columns:
      - name: subscription_id
        tests:
          - not_null
          - unique

      - name: account_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_accounts')
                field: account_id


  - name: stg_feature_usage
    description: Daily aggregated feature usage per subscription

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - subscription_id
              - usage_date
              - feature_name

    columns:
      - name: subscription_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_subscriptions')
                field: subscription_id


  - name: stg_churn_events
    description: Cleaned staging model for churn events

    columns:
      - name: churn_event_id
        tests:
          - not_null
          - unique

      - name: account_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_accounts')
                field: account_id


  - name: stg_support_tickets
    description: Cleaned staging model for support tickets

    columns:
      - name: ticket_id
        tests:
          - not_null
          - unique

      - name: account_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_accounts')
                field: account_id
